### ISSUE TITLE
Server counter

### ISSUE THREAD

**Issue by ShowMeYourSkil** [ProgenBot/ProgenBot#74]
*Make feature server counter for Progen possible*
*The pom.xml has already been updated correspondingly.*

**Useful link**
<https://top.gg/api/docs#bots>
<https://github.com/DiscordBotList/DBL-Java-Library>
![unknown](https://user-images.githubusercontent.com/39274150/73124128-f0c0cc00-3f97-11ea-82c4-96c3917391b2.png)

**Comment by HGotthard** [comment]
3b784214b3c4965d58e6cc0aadac49135c5f3b1d
